### ISSUE TITLE
Slice bounds out of range when using commit

### ISSUE THREAD

**Issue by Tyndie** [LyricalSecurity/gigo#9]
Hi,

Just been trying out using a commit as a requirement with my own repos, and with the examples that are provided, and I get this error each time:

Installing github.com/BurntSushi/toml
Installing git@github.com:kr/fs#2788f0
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/LyricalSecurity/gigo/actions.RcsGet(0xc8200941cb, 0x1b)
	/home/vagrant/go/src/github.com/LyricalSecurity/gigo/actions/rcsget.go:30 +0x4dd
github.com/LyricalSecurity/gigo/actions.installPackages(0xc8200124b0, 0x3, 0x3)
	/home/vagrant/go/src/github.com/LyricalSecurity/gigo/actions/install.go:60 +0x1e9
github.com/LyricalSecurity/gigo/actions.Install(0xc82009c0f0)
	/home/vagrant/go/src/github.com/LyricalSecurity/gigo/actions/install.go:33 +0x2eb
github.com/codegangsta/cli.Command.Run(0x5b5530, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5d2650, 0x10, 0x0, ...)
	/home/vagrant/go/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc820096000, 0xc82000a1c0, 0x4, 0x4, 0x0, 0x0)
	/home/vagrant/go/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/home/vagrant/go/src/github.com/LyricalSecurity/gigo/main.go:47 +0x411

**Comment by hvnsweeting** [comment]
Hi, I got the same problem here.

The given example one is not well-formed git link, the good one should has suffix ``.git``. E.g:

``git@github.com:LyricalSecurity/gigo.git``

Adding .git make it pass the error:

````
gigo install git@github.com:kr/fs.git#2788f0
Installing git@github.com:kr/fs.git#2788f0
Cloning into 'src/fs'...
remote: Counting objects: 18, done.
remote: Total 18 (delta 0), reused 0 (delta 0), pack-reused 18
Receiving objects: 100% (18/18), 6.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (7/7), done.
Checking connectivity... done.
````

but anyway, I don't see it checkout to the commit:

````
$ cd src/fs
$ git branch
* master
````

And the package path also bad handled. It should be src/github.com/kr/fs
